spring.application.name=MoneyManager

#H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/moneymanager;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

server.servlet.context-path=/api/v1.0

#JPA Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Email Configuration (Defaulting to SendGrid for Render Port 2525 compatibility)
spring.mail.host=${SPRING_MAIL_HOST:smtp.sendgrid.net}
spring.mail.port=${SPRING_MAIL_PORT:2525}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp

# The email address that emails will be sent from (e.g. your verified Brevo or SendGrid email)
app.mail.sender=${APP_MAIL_SENDER:your_verified_email@example.com}

jwt.secret = bd1a9a93-ef5c-45b3-bae5-98213dd7cd28

money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL:http://localhost:5173}

app.activation.url=${MONEY_MANAGER_BACKEND_URL:http://localhost:8080}

gemini.api.key=${GEMINI_API_KEY:}

# spring.profiles.active = prod

server.port=${PORT:8080}

